version: '3'
services:
  kinsjen:
    image: anshooarora/kinsjen:latest
    container_name: kinsjen
    environment:
      - "SPRING_PROFILES_ACTIVE=mysql"
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/kinsjen?autoReconnect=true
      - SPRING_DATASOURCE_DRIVERCLASSNAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - 80:80
