version: '3'
services:
  kinsjen:
    image: anshooarora/kinsjen:latest
    container_name: kinsjen
    environment:
      - "SPRING_PROFILES_ACTIVE=h2"
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/db
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
    ports:
      - 80:80
