server:
  port: 80
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # [ validate, create, update, none, create-drop ]
  datasource:
    hikari:
      maxLifeTime: 30000
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: INFO
